### ISSUE TITLE
跑不起来的嘛

### ISSUE THREAD

**Issue by ruige714111** [programbao/lottery-electron-vite-vue#2]
在npm i 就失败了

**Comment by programbao** [comment]
你的npm和node是啥版本呢？建议版本是node(18.16.0)，npm(9.5.1)

**Comment by programbao** [comment]
@ruige714111 你的npm和node是啥版本呢？建议版本是node(18.16.0)，npm(9.5.1)

**Comment by ruige714111** [comment]
> @ruige714111 你的npm和node是啥版本呢？建议版本是node(18.16.0)，npm(9.5.1)

好吧  我是14.21  6.14 版本太低了是不是

**Comment by programbao** [comment]
@ruige714111 是的，你升级一下再试试
