### ISSUE TITLE
[Help] 运行以后，弹窗报错

### ISSUE THREAD

**Issue by panzhimin666** [programbao/lottery-electron-vite-vue#3]
![error](https://github.com/programbao/lottery-electron-vite-vue/assets/33124536/77496393-3ae6-4c2b-9d63-ba0398bb8997)
运行以后，弹窗报错

**Comment by programbao** [comment]
@panzhimin666 可能你下载的依赖有问题；请重新下载依赖 并删除dist和dist-electron文件，再运行试试 ；还有运行版本是node(18.16.0) 及以上，npm(9.5.1) 及以上

**Comment by panzhimin666** [comment]
@programbao 我npm run dev 之后为啥dist-electron/main目录没有生成index.mjs
![1705396050374](https://github.com/programbao/lottery-electron-vite-vue/assets/33124536/bfd4ce24-4f46-44f9-8e0e-4d2266636082)

**Comment by programbao** [comment]
@panzhimin666 这个是运行之后才生成的； 拉一下最新代码，把dist-electron和.vscode->.debug.env都删掉；然后重启编辑器 再试一下吧
