### ISSUE TITLE
[Help] 启动一直报错Uncaught (in promise) ReferenceError: myApi is not defined

### ISSUE THREAD

**Issue by jck9** [programbao/lottery-electron-vite-vue#5]
#### Describe the problem you confuse
启动一直报错，已经卡了一天了，报错：Uncaught (in promise) ReferenceError: myApi is not defined，
谷歌浏览器版本v120.0
node版本v18.17.0

<img width="1439" alt="image" src="https://github.com/programbao/lottery-electron-vite-vue/assets/35520240/5cfc1b81-16e9-4edc-b7ed-6fc52d30bb5a">
<img width="1074" alt="image" src="https://github.com/programbao/lottery-electron-vite-vue/assets/35520240/06cf2314-a309-4fd0-8cce-a97a25b46163">
<img width="1102" alt="image" src="https://github.com/programbao/lottery-electron-vite-vue/assets/35520240/d448fe96-c49c-4513-95f8-d8f2cb3722ff">

**Comment by jck9** [comment]
> @jck9删掉dist和dist-电子可以重新运行吗？

删掉也不能运行，还是同样的错误

**Comment by programbao** [comment]
@jck9 已同步跟新配置了，可以拉最新代码 再试一下

**Comment by jck9** [comment]
> @jck9 已同步跟新配置了，可以拉最新代码 再试一下

重新拉下项目，现在可以正常访问了，感谢大佬
